apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Values.name }}-pod"
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
