availableSecrets:
  secretManager:
    - versionName: projects/520359608438/secrets/github-token-secret/versions/latest
      env: "PAT"
steps:
  - name: "gcr.io/cloud-builders/git"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Cloning GitHub repo with PAT..."
        git clone https://oauth2:${PAT}@github.com/Karthik-Nayak98/frontend-backend-devops.git
        cd frontend-backend-devops 
        echo "Repo cloned successfully"
    secretEnv: ["PAT"]
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Frontend Container Image"
    args:
      [
        "build",
        "-t",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/frontend/${_IMAGE_TAG}:latest",
        ".",
      ]
    dir: frontend

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Backend Container Image"
    args:
      [
        "build",
        "-t",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/backend/${_IMAGE_TAG}:latest",
        ".",
      ]
    dir: backend

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Frontend Container Image to Artifact Registry"
    args:
      [
        "push",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/frontend/${_IMAGE_TAG}:latest",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Backend Container Image to Artifact Registry"
    args:
      [
        "push",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/backend/${_IMAGE_TAG}:latest",
      ]
options:
  # Using CLOUD_LOGGING_ONLY restricts build logs to Google Cloud Logging only.
  logging: CLOUD_LOGGING_ONLY
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/backend/${_IMAGE_TAG}:latest"
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/frontend/${_IMAGE_TAG}:latest"
