availableSecrets:
  secretManager:
  - versionName: projects/520359608438/secrets/github-token-secret/varsions/latest
    env: 'PAT'

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: 'Build Container Image'
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_ARTIFACTORY}:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: 'Push Container Image to Artifact Registry'
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_ARTIFACTORY}:latest",
      ]