steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Frontend Container Image"
    args:
      - "build"
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"
      - "."
    dir: frontend

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Backend Container Image"
    args:
      - "build"
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
      - "."
    dir: backend
  - name: "gcr.io/cloud-builders/docker"
    id: Push frontend image
    args:
      - "push"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    id: Push backend image
    args:
      - "push"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Authenticate to the GKE cluster"
    entrypoint: "bash"
    env:
      - USE_GKE_GCLOUD_AUTH_PLUGIN=True
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials ${_GKE_CLUSTER} \
          --location ${_ZONE} \
          --project $PROJECT_ID
  # 4. Deploy backend using Helm
  - name: "alpine/helm:3.14.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd helm/backend
        helm upgrade --install backend ./Chart.yaml \
          --set image.repository="$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}" \
          --set image.tag="$SHORT_SHA"
  # 4. Deploy frontend using Helm
  - name: "alpine/helm:3.14.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd helm/frontend
        helm upgrade --install backend ./Chart.yaml \
          --set image.repository="$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}" \
          --set image.tag="$SHORT_SHA"
options:
  # Using CLOUD_LOGGING_ONLY restricts build logs to Google Cloud Logging only.
  logging: CLOUD_LOGGING_ONLY
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"
