steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Frontend Container Image"
    args:
      - "build"
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"
      - "."
    dir: frontend

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Backend Container Image"
    args:
      - "build"
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
      - "."
    dir: backend
  - name: "gcr.io/cloud-builders/docker"
    id: Push frontend image
    args:
      - "push"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    id: Push backend image
    args:
      - "push"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
options:
  # Using CLOUD_LOGGING_ONLY restricts build logs to Google Cloud Logging only.
  logging: CLOUD_LOGGING_ONLY
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"
