steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Frontend Container Image"
    args:
      - "build"
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"
      - "."
    dir: frontend

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Backend Container Image"
    args:
      - "build"
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
      - "."
    dir: backend
  - name: "gcr.io/cloud-builders/docker"
    id: Push frontend image
    args:
      - "push"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    id: Push backend image
    args:
      - "push"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Authenticate to the GKE cluster"
    entrypoint: "bash"
    env:
      - USE_GKE_GCLOUD_AUTH_PLUGIN=True
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials ${_GKE_CLUSTER} \
          --location ${_ZONE} \
          --project $PROJECT_ID

        curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

        # Deploy backend using Helm
        cd helm/backend
        helm upgrade --install backend . \
          --set image.repository="$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}" \
          --set image.tag="$SHORT_SHA"

        cd ../..

        # Deploy frontend using Helm
        cd helm/frontend
        helm upgrade --install frontend . \
          --set image.repository="$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}" \
          --set image.tag="$SHORT_SHA"
options:
  # Using CLOUD_LOGGING_ONLY restricts build logs to Google Cloud Logging only.
  logging: CLOUD_LOGGING_ONLY
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/backend/${_IMAGE_NAME}:$SHORT_SHA"
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/${_ARTIFACTORY}/frontend/${_IMAGE_NAME}:$SHORT_SHA"
