apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-todo-deployment
  labels:
    app: frontend-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-todo
  template:
    metadata:
      labels:
        app: frontend-todo
    spec:
      containers:
      - name: frontend-todo-container
        image: 94822karthik/frontend-todo:latest
        ports:
        - containerPort: 3000 

