apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.name }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "gce"   # if using GKE
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.name }}-service"
                port:
                  number: 80
          - path: /tasks
            pathType: Prefix
            backend:
              service:
                name: backend-todo-service
                port:
                  number: 8000