apiVersion: v1
kind: Service
metadata:
  name: "{{ .Value.name }}-service"
spec:
  type: LoadBalancer
  selector:
    app: { { .Value.name } }
  ports:
    - port: 80
      targetPort: { { .Value.containerPort } }
      protocol: TCP
