
name: Run the static tests for the Frontend and Backend application.

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on:  ubuntu-latest
    permissions:
      content: read
    
    steps:
      - name: Checkout backend code. 
        uses: actions/checkout@v4
      
      - name: Setup python environment
        uses: actions/setup-python@v5

      - name: Install required dependencies
        run: |
             cd backend
             python -m pip install --upgrade pip
             pip install -r requirements.txt
      
      - name: Run the python testing
        run: |
          cd backend
          python3 -m pytest app_test.py
