name: Containerize, Push, and Deploy the Application
on: 
  workflow_dispatch:

env: 
  REGISTRY: ghcr.io
jobs:
    containerize:
        runs-on: ubuntu-latest
    
        permissions:
            id-token: write
            contents: read
        
        steps:
            - name: Checkout the code. 
              uses: actions/checkout@v4
            
            - name: Login to dockerhub
              uses: docker/login-action@v2
              with: 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Get the metadata for Docker
              id: meta-frontend
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with: 
                images: ${{ env.REGISTRY }}/frontend-todo 
            - name: Build and push the frontend image to docker hub 
              uses: docker/build-push-action@v6
              with: 
                context: frontend
                push: true
                tag: ${{ steps.meta-frontend.outputs.tags }} 

               
