name: Run the static tests for the Frontend and Backend application.

on:
  push:
    branches: 
      - main
jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout backend code.
        uses: actions/checkout@v4

      - name: Setup python environment
        uses: actions/setup-python@v5

      - name: Install required dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the python testing
        run: |
          cd backend
          python3 -m pytest app_test.py

  frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Setup Node js environment
        uses: actions/setup-node@v4

      - name: Install required dependencies
        run: |
          cd frontend 
          npm install

      - name: Run linting and formatting
        run: |
          cd frontend 
          npm run lint && npm run lint:fix
          npm run format
      - name: Run the tests for React
        run: |
          cd frontend 
          npm test
          npm run coverage
